# Form implementation generated from reading ui file 'f:\QT\UI_rjtt\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(845, 717)
        login.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        login.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        self.centralwidget = QtWidgets.QWidget(parent=login)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 20, 481, 651))
        self.label.setStyleSheet("border-image: url(./image/background.png);\n"
"border-radius:30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(280, 330, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(0, 0, 0, 100);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 430, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(0, 0, 0, 100);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(280, 510, 93, 24))
        self.checkBox.setStyleSheet("/* 未选中状态：浅色、虚线边框，无内容 */\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 1px solid rgba(0, 0, 0, 1);\n"
"}\n"
"\n"
"/* 选中状态：深色、实线边框，显示对钩 */\n"
"QCheckBox::indicator:checked {\n"
"    border: 1px solid rgba(0, 0, 0, 1);\n"
"    border-image: url(./image/mark.png);\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(470, 510, 93, 24))
        self.checkBox_2.setStyleSheet("/* 未选中状态：浅色、虚线边框，无内容 */\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: 1px solid rgba(0, 0, 0, 1);\n"
"}\n"
"\n"
"/* 选中状态：深色、实线边框，显示对钩 */\n"
"QCheckBox::indicator:checked {\n"
"    border: 1px solid rgba(0, 0, 0, 1);\n"
"    border-image: url(./image/mark.png);\n"
"}")
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 550, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(75, 126, 232);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 160, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 210, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 640, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(619, 30, 31, 31))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    image: url(./image/x.png);\n"
"    border-radius:30px;\n"
"    border: none;\n"
"}\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=login)
        self.statusbar.setObjectName("statusbar")
        login.setStatusBar(self.statusbar)

        self.retranslateUi(login)
        self.pushButton_2.clicked.connect(login.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("login", "帐号："))
        self.lineEdit_2.setPlaceholderText(_translate("login", "密码："))
        self.checkBox.setText(_translate("login", "记住密码"))
        self.checkBox_2.setText(_translate("login", "自动登陆"))
        self.pushButton.setText(_translate("login", "登陆"))
        self.label_2.setText(_translate("login", "安检监控系统"))
        self.label_3.setText(_translate("login", "请登陆以继续"))
        self.label_4.setText(_translate("login", "© 2026 安检监控系统. 保留所有权利."))
