# Form implementation generated from reading ui file 'f:\QT\UI_rjtt\math.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_math(object):
    def setupUi(self, Form_math):
        Form_math.setObjectName("Form_math")
        Form_math.resize(1366, 715)
        Form_math.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Form_math.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("f:\\QT\\UI_rjtt\\ruijian_logo_v2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_math.setWindowIcon(icon)
        Form_math.setStyleSheet("QWidget#Form_math{\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 30px; \n"
"}")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form_math)
        self.stackedWidget.setGeometry(QtCore.QRect(9, 68, 1328, 591))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.tableWidget_1 = QtWidgets.QTableWidget(parent=self.page_1)
        self.tableWidget_1.setGeometry(QtCore.QRect(0, -1, 631, 591))
        self.tableWidget_1.setStyleSheet("")
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(5)
        self.tableWidget_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(4, item)
        self.chart_1 = PlotWidget(parent=self.page_1)
        self.chart_1.setGeometry(QtCore.QRect(630, 20, 691, 271))
        self.chart_1.setStyleSheet("border: 1px solid rgb(75, 127, 232);\n"
"border-radius:30px;\n"
"")
        self.chart_1.setObjectName("chart_1")
        self.label_1 = QtWidgets.QLabel(parent=self.page_1)
        self.label_1.setGeometry(QtCore.QRect(630, 0, 681, 16))
        self.label_1.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius:30px;\n"
"")
        self.label_1.setObjectName("label_1")
        self.chart_11 = QtWidgets.QTableWidget(parent=self.page_1)
        self.chart_11.setGeometry(QtCore.QRect(630, 290, 691, 301))
        self.chart_11.setStyleSheet("border: 1px solid rgb(75, 127, 232);\n"
"border-radius:30px;\n"
"\n"
"background-color: transparent;")
        self.chart_11.setObjectName("chart_11")
        self.chart_11.setColumnCount(0)
        self.chart_11.setRowCount(0)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.page_2)
        self.tableWidget_2.setEnabled(True)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, -1, 630, 611))
        self.tableWidget_2.setStyleSheet("")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.chart_2 = PlotWidget(parent=self.page_2)
        self.chart_2.setGeometry(QtCore.QRect(630, 20, 691, 271))
        self.chart_2.setStyleSheet("border: 1px solid rgb(75, 127, 232);\n"
"border-radius:30px;\n"
"\n"
"")
        self.chart_2.setObjectName("chart_2")
        self.label_2 = QtWidgets.QLabel(parent=self.page_2)
        self.label_2.setGeometry(QtCore.QRect(630, 0, 681, 16))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.chart_21 = QtWidgets.QTableWidget(parent=self.page_2)
        self.chart_21.setGeometry(QtCore.QRect(630, 290, 691, 301))
        self.chart_21.setStyleSheet("background-color: transparent;\n"
"border: 1px solid rgb(75, 127, 232);\n"
"border-radius:30px;\n"
"")
        self.chart_21.setObjectName("chart_21")
        self.chart_21.setColumnCount(0)
        self.chart_21.setRowCount(0)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(parent=self.page_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, -1, 630, 611))
        self.tableWidget_3.setStyleSheet("")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.label_3 = QtWidgets.QLabel(parent=self.page_3)
        self.label_3.setGeometry(QtCore.QRect(630, 0, 681, 16))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.chart_3 = PlotWidget(parent=self.page_3)
        self.chart_3.setGeometry(QtCore.QRect(630, 20, 691, 271))
        self.chart_3.setStyleSheet("border: 1px solid rgb(75, 127, 232);\n"
"border-radius:30px;\n"
"")
        self.chart_3.setObjectName("chart_3")
        self.chart_31 = QtWidgets.QTableWidget(parent=self.page_3)
        self.chart_31.setGeometry(QtCore.QRect(630, 290, 691, 301))
        self.chart_31.setStyleSheet("background-color: transparent;\n"
"border: 1px solid rgb(75, 127, 232);\n"
"border-radius:30px;\n"
"\n"
"")
        self.chart_31.setObjectName("chart_31")
        self.chart_31.setColumnCount(0)
        self.chart_31.setRowCount(0)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.tableWidget_4 = QtWidgets.QTableWidget(parent=self.page_4)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, -1, 630, 591))
        self.tableWidget_4.setStyleSheet("background-color: transparent;\n"
"\n"
"\n"
"")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        self.chart_4 = PlotWidget(parent=self.page_4)
        self.chart_4.setGeometry(QtCore.QRect(630, 20, 691, 271))
        self.chart_4.setStyleSheet("border: 1px solid rgb(75, 127, 232);\n"
"border-radius:30px;\n"
"")
        self.chart_4.setObjectName("chart_4")
        self.label_4 = QtWidgets.QLabel(parent=self.page_4)
        self.label_4.setGeometry(QtCore.QRect(630, 0, 691, 16))
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.chart_41 = QtWidgets.QTableWidget(parent=self.page_4)
        self.chart_41.setGeometry(QtCore.QRect(630, 290, 691, 301))
        self.chart_41.setStyleSheet("background-color: transparent;\n"
"border: 1px solid rgb(75, 127, 232);\n"
"border-radius:30px;\n"
"\n"
"")
        self.chart_41.setObjectName("chart_41")
        self.chart_41.setColumnCount(0)
        self.chart_41.setRowCount(0)
        self.stackedWidget.addWidget(self.page_4)
        self.label_5 = QtWidgets.QLabel(parent=Form_math)
        self.label_5.setGeometry(QtCore.QRect(90, 10, 1241, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(75, 127, 232);")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(parent=Form_math)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    image: url(./image/z.png);\n"
"    border-radius:30px;\n"
"    border: none;\n"
"}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(parent=Form_math)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 35, 1321, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_1 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_1.setStyleSheet("border: 1px solid rgb(75, 127, 232);\n"
"border-radius:30px;\n"
"color: rgb(75, 126, 232);")
        self.pushButton_1.setCheckable(True)
        self.pushButton_1.setObjectName("pushButton_1")
        self.buttonGroup = QtWidgets.QButtonGroup(Form_math)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton_1)
        self.horizontalLayout.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_2.setStyleSheet("border: 1px solid rgb(75, 127, 232);\n"
"border-radius:30px;\n"
"color: rgb(75, 126, 232);")
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.buttonGroup.addButton(self.pushButton_2)
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_3.setStyleSheet("border: 1px solid rgb(75, 127, 232);\n"
"border-radius:30px;\n"
"color: rgb(75, 126, 232);")
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.buttonGroup.addButton(self.pushButton_3)
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_4.setStyleSheet("border: 1px solid rgb(75, 127, 232);\n"
"border-radius:30px;\n"
"color: rgb(75, 126, 232);")
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.buttonGroup.addButton(self.pushButton_4)
        self.horizontalLayout.addWidget(self.pushButton_4)

        self.retranslateUi(Form_math)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form_math)

    def retranslateUi(self, Form_math):
        _translate = QtCore.QCoreApplication.translate
        Form_math.setWindowTitle(_translate("Form_math", "数据统计"))
        item = self.tableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("Form_math", "违禁品类型"))
        item = self.tableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("Form_math", "具体类别"))
        item = self.tableWidget_1.horizontalHeaderItem(2)
        item.setText(_translate("Form_math", "数量"))
        item = self.tableWidget_1.horizontalHeaderItem(3)
        item.setText(_translate("Form_math", "单位"))
        item = self.tableWidget_1.horizontalHeaderItem(4)
        item.setText(_translate("Form_math", "最后检测时间"))
        self.label_1.setText(_translate("Form_math", "每天违禁品数量趋势"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form_math", "违禁品类型"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form_math", "具体类别"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form_math", "数量"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form_math", "单位"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form_math", "最后检测时间"))
        self.label_2.setText(_translate("Form_math", "每周违禁品数量趋势"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form_math", "违禁品类型"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Form_math", "具体类别"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Form_math", "数量"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Form_math", "单位"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("Form_math", "最后检测时间"))
        self.label_3.setText(_translate("Form_math", "月违禁品数量趋势"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Form_math", "违禁品类型"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Form_math", "具体类别"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("Form_math", "数量"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("Form_math", "单位"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("Form_math", "最后检测时间"))
        self.label_4.setText(_translate("Form_math", "每年违禁品数量趋势"))
        self.label_5.setText(_translate("Form_math", "本机违禁品统计"))
        self.pushButton_1.setText(_translate("Form_math", "今日"))
        self.pushButton_2.setText(_translate("Form_math", "近7天"))
        self.pushButton_3.setText(_translate("Form_math", "近1个月"))
        self.pushButton_4.setText(_translate("Form_math", "近1年"))
from pyqtgraph import PlotWidget
